GET http://localhost:5234/kaka
###
Get http://localhost:5234/Test/TestMethod

###
GET http://localhost:5234/Test/DoThings
###

POST http://localhost:5234/Test/DoThings1
###
POST http://localhost:5234/auth/register
Content-Type: application/json

{
    "login": "TestAccountTwink",
    "password": "TestPassword"
}
###
POST  http://localhost:5234/auth/set-information
Content-Type: application/json

{
    "id": 1,
    "surname": "Dmitriev",
    "name": "Artyom",
    "gender": "male",
    "dateOfBirth": "2120-10-11"
}