GET http://localhost:5234/kaka
###
Get http://localhost:5234/Test/TestMethod

###
POST http://localhost:5234/Test/DoThings
###

POST http://localhost:5234/Test/DoThings1
###
POST http://localhost:5234/auth/register
Content-Type: application/json

{
    "login": "TestAccountTwink",
    "password": "TestPassword"
}
###
POST http://localhost:5234/auth/set-information
Content-Type: application/json

{
    "id": 1,
    "surname": "Dmitriev",
    "name": "Artyom",
    "gender": "male",
    "dateOfBirth": "2120-10-11"
}
###
GET http://localhost:5234/personal-account/7
###
PUT http://localhost:5234/personal-account/edit
Content-Type: application/json

{
    "id": 21,
    "surname": "Dmitriev",
    "name": "ArtyomTest",
    "gender": "male",
    "description": "Бутстрап говно снова",
    "cityId": 1,
    "dateOfBirth": "2005-08-31",
    "favouriteSportsId": [1]
}
###
POST http://localhost:5234/tournaments/create
Content-Type: application/json

{
    "name": "Test Name",
    "typeOfSport": 1,
    "format": 1,
    "placement": "Жопа дракона",
    "startDate": "2024-08-10",
    "endTime": "2024-08-12",
    "description": "Я люблю какать",
    "contacts": "Я не придумал",
    "registrationDeadline": "2005-08-31T10:20:00Z"
}

###
GET http://localhost:5234/sports
###
GET http://localhost:5234/formats
###
GET http://localhost:5234/cities
###
POST http://localhost:5234/cities/create
Content-Type: application/json

{
    "name": "Нижний Новгород"
}
###
GET http://localhost:5234/tournaments/get?cityId=1&sportId=1&status=ended&isPrivate=false
###
GET http://localhost:5234/tournaments/get/4
###
http://localhost:5234/swagger/index.html