CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE TABLE "Cities" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        CONSTRAINT "PK_Cities" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE TABLE "Dates" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Start" date NOT NULL,
        "End" date NOT NULL,
        CONSTRAINT "PK_Dates" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE TABLE "FavouriteSports" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text,
        CONSTRAINT "PK_FavouriteSports" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE TABLE "Formats" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Structure" text NOT NULL,
        CONSTRAINT "PK_Formats" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE TABLE "Notifications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Text" text NOT NULL,
        "DateOfSending" date NOT NULL,
        CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE TABLE "Roles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text,
        "IsTeamRole" boolean NOT NULL,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE TABLE "Sports" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text,
        CONSTRAINT "PK_Sports" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE TABLE "Statuses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        CONSTRAINT "PK_Statuses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE TABLE "Teams" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "TeamsUsersId" integer NOT NULL,
        CONSTRAINT "PK_Teams" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE TABLE "Locations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CityId" integer NOT NULL,
        "Street" text NOT NULL,
        "SportObjectName" text NOT NULL,
        CONSTRAINT "PK_Locations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Locations_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES "Cities" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Login" text NOT NULL,
        "Password" text NOT NULL,
        "RoleId" integer NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE TABLE "TeamsUsers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TeamId" integer NOT NULL,
        "DateOfRegistration" date NOT NULL,
        "IsFull" boolean NOT NULL,
        "RoleId" integer NOT NULL,
        CONSTRAINT "PK_TeamsUsers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TeamsUsers_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TeamsUsers_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE TABLE "Tournaments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text,
        "DateId" integer NOT NULL,
        "LocationId" integer NOT NULL,
        "IsPrivate" boolean NOT NULL,
        "SportId" integer NOT NULL,
        "FormatId" integer NOT NULL,
        "NotificationId" integer NOT NULL,
        "Link" text NOT NULL,
        CONSTRAINT "PK_Tournaments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Tournaments_Dates_DateId" FOREIGN KEY ("DateId") REFERENCES "Dates" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Tournaments_Formats_FormatId" FOREIGN KEY ("FormatId") REFERENCES "Formats" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Tournaments_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES "Locations" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Tournaments_Notifications_NotificationId" FOREIGN KEY ("NotificationId") REFERENCES "Notifications" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Tournaments_Sports_SportId" FOREIGN KEY ("SportId") REFERENCES "Sports" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE TABLE "UserInfos" (
        "UserId" integer NOT NULL,
        "Name" text NOT NULL,
        "Surname" text NOT NULL,
        "Birthday" date NOT NULL,
        "CityId" integer NOT NULL,
        "Description" text,
        CONSTRAINT "PK_UserInfos" PRIMARY KEY ("UserId"),
        CONSTRAINT "FK_UserInfos_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES "Cities" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserInfos_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE TABLE "TeamUsersUser" (
        "TeamsUsersId" integer NOT NULL,
        "UsersId" integer NOT NULL,
        CONSTRAINT "PK_TeamUsersUser" PRIMARY KEY ("TeamsUsersId", "UsersId"),
        CONSTRAINT "FK_TeamUsersUser_TeamsUsers_TeamsUsersId" FOREIGN KEY ("TeamsUsersId") REFERENCES "TeamsUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TeamUsersUser_Users_UsersId" FOREIGN KEY ("UsersId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE TABLE "Requests" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TournamentId" integer,
        "StatusId" integer NOT NULL,
        "Date" date NOT NULL,
        "TeamUsersId" integer NOT NULL,
        CONSTRAINT "PK_Requests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Requests_Statuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES "Statuses" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Requests_TeamsUsers_TeamUsersId" FOREIGN KEY ("TeamUsersId") REFERENCES "TeamsUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Requests_Tournaments_TournamentId" FOREIGN KEY ("TournamentId") REFERENCES "Tournaments" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE TABLE "FavouriteSportUserInfo" (
        "FavouriteSportsId" integer NOT NULL,
        "UserInfosUserId" integer NOT NULL,
        CONSTRAINT "PK_FavouriteSportUserInfo" PRIMARY KEY ("FavouriteSportsId", "UserInfosUserId"),
        CONSTRAINT "FK_FavouriteSportUserInfo_FavouriteSports_FavouriteSportsId" FOREIGN KEY ("FavouriteSportsId") REFERENCES "FavouriteSports" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FavouriteSportUserInfo_UserInfos_UserInfosUserId" FOREIGN KEY ("UserInfosUserId") REFERENCES "UserInfos" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE INDEX "IX_FavouriteSportUserInfo_UserInfosUserId" ON "FavouriteSportUserInfo" ("UserInfosUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE INDEX "IX_Locations_CityId" ON "Locations" ("CityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE INDEX "IX_Requests_StatusId" ON "Requests" ("StatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE INDEX "IX_Requests_TeamUsersId" ON "Requests" ("TeamUsersId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE INDEX "IX_Requests_TournamentId" ON "Requests" ("TournamentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE INDEX "IX_TeamsUsers_RoleId" ON "TeamsUsers" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE UNIQUE INDEX "IX_TeamsUsers_TeamId" ON "TeamsUsers" ("TeamId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE INDEX "IX_TeamUsersUser_UsersId" ON "TeamUsersUser" ("UsersId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE INDEX "IX_Tournaments_DateId" ON "Tournaments" ("DateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE INDEX "IX_Tournaments_FormatId" ON "Tournaments" ("FormatId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE INDEX "IX_Tournaments_LocationId" ON "Tournaments" ("LocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE INDEX "IX_Tournaments_NotificationId" ON "Tournaments" ("NotificationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE INDEX "IX_Tournaments_SportId" ON "Tournaments" ("SportId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE INDEX "IX_UserInfos_CityId" ON "UserInfos" ("CityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129064659_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241129064659_Initial', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241129065139_TempMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241129065139_TempMigration', '9.0.0');
    END IF;
END $EF$;
COMMIT;

